INSERT INTO usuario (id, username, password, account_non_locked)
VALUES (1, 'admin', '$2a$10$0HPsbIfHuDHUcZXibsIfbe7SfzBj5MPinSifc4oXWOklILNTmnMT2', true)
ON CONFLICT DO NOTHING;

INSERT INTO sexo (descricao)
VALUES ('Masculino'),
       ('Feminino'),
       ('Outro')
ON CONFLICT DO NOTHING;

INSERT INTO estado_civil (descricao)
VALUES ('Solteiro'),
       ('Casado'),
       ('Divorciado'),
       ('Separado'),
       ('Viúvo')
ON CONFLICT DO NOTHING;

INSERT INTO raca (descricao)
VALUES ('Preto'),
       ('Pardo'),
       ('Branco'),
       ('Amarelo'),
       ('Indígena')
ON CONFLICT DO NOTHING;

INSERT INTO pais (descricao)
VALUES (' Afeganistão '),
       (' África do Sul '),
       (' Aland, Ilhas '),
       (' Albania, República da '),
       (' Alemanha '),
       (' Andorra '),
       (' Angola '),
       (' Anguilla '),
       (' Antártica '),
       (' Antígua e Barbuda '),
       (' Arábia Saudita '),
       (' Argélia '),
       (' Argentina '),
       (' Armênia, República da '),
       (' Aruba '),
       (' Austrália '),
       (' Áustria '),
       (' Azerbaijão, República do '),
       (' Bahamas, Ilhas '),
       (' Bahrein, Ilhas '),
       (' Bangladesh '),
       (' Barbados '),
       (' Belarus, República da '),
       (' Bélgica '),
       (' Belize '),
       (' Benin '),
       (' Bermudas '),
       (' Bolívia, Estado Plurinacional da '),
       (' Bonaire, Saint Eustatius e Saba '),
       (' Bósnia '),
       (' Botsuana '),
       (' Bouvet, Ilha '),
       (' Brasil '),
       (' Brunei '),
       (' Bulgária, RepúblCREATE SCHEMA IF NOT EXISTS "pessoa";ica da '),
       (' Burkina Faso '),
       (' Burundi '),
       (' Butão '),
       (' Cabo Verde, República de '),
       (' Camarões '),
       (' Camboja '),
       (' Canadá '),
       (' Catar '),
       (' Cayman, Ilhas '),
       (' Cazaquistão, República do '),
       (' Chade '),
       (' Chile '),
       (' China, República Popular '),
       (' Chipre '),
       (' Christmas, Ilha (Navidad) '),
       (' Cingapura '),
       (' Cocos (Keeling), Ilhas '),
       (' Colômbia '),
       (' Comores, Ilhas '),
       (' Congo '),
       (' Congo, República Democrática do '),
       (' Cook, Ilhas '),
       (' Coreia (do Norte), Rep. Pop. Democrática '),
       (' Coreia (do Sul), República da '),
       (' Costa do Marfim '),
       (' Costa Rica '),
       (' Croácia, República da '),
       (' Cuba '),
       (' Curacao '),
       (' Dinamarca '),
       (' Djibuti '),
       (' Dominica, Ilha '),
       (' Egito '),
       (' El Salvador '),
       (' Emirados Árabes Unidos '),
       (' Equador '),
       (' Eritreia '),
       (' Eslovaca, República '),
       (' Eslovênia, República da '),
       (' Espanha '),
       (' Estados Unidos '),
       (' Estônia, República da '),
       (' eSwatini '),
       (' Etiópia '),
       (' Falkland (Ilhas Malvinas) '),
       (' Feroe, Ilhas '),
       (' Fiji '),
       (' Filipinas '),
       (' Finlândia '),
       (' Formosa (Taiwan) '),
       (' França '),
       (' Gabão '),
       (' Gâmbia '),
       (' Gana '),
       (' Geórgia do Sul e Sandwich do Sul, Ilhas '),
       (' Geórgia, República da '),
       (' Gibraltar '),
       (' Granada '),
       (' Grécia '),
       (' Groenlândia '),
       (' Guadalupe '),
       (' Guam '),
       (' Guatemala '),
       (' Guernsey '),
       (' Guiana '),
       (' Guiana Francesa '),
       (' Guiné '),
       (' Guiné '),
       (' Guiné '),
       (' Haiti '),
       (' Heard e Ilhas McDonald, Ilha '),
       (' Honduras '),
       (' Hong Kong '),
       (' Hungria, República da '),
       (' Iêmen '),
       (' Índia '),
       (' Indonésia '),
       (' Irã, República Islâmica do '),
       (' Iraque '),
       (' Irlanda '),
       (' Islândia '),
       (' Israel '),
       (' Itália '),
       (' Jamaica '),
       (' Japão '),
       (' Jersey '),
       (' Jordânia '),
       (' Kiribati '),
       (' Kuwait '),
       (' Laos, Rep. Pop. Democr. do '),
       (' Lesoto '),
       (' Letônia, República da '),
       (' Líbano '),
       (' Libéria '),
       (' Líbia '),
       (' Liechtenstein '),
       (' Lituânia, República da '),
       (' Luxemburgo '),
       (' Macau '),
       (' Macedônia do Norte '),
       (' Madagascar '),
       (' Malásia '),
       (' Malavi '),
       (' Maldivas '),
       (' Mali '),
       (' Malta '),
       (' Man, Ilha de '),
       (' Marianas do Norte '),
       (' Marrocos '),
       (' Marshall, Ilhas '),
       (' Martinica '),
       (' Maurício '),
       (' Mauritânia '),
       (' Mayotte '),
       (' México '),
       (' Mianmar (Birmânia) '),
       (' Micronésia '),
       (' Moçambique '),
       (' Moldávia, República da '),
       (' Mônaco '),
       (' Mongólia '),
       (' Montenegro '),
       (' Montserrat, Ilhas '),
       (' Namíbia '),
       (' Nauru '),
       (' Nepal '),
       (' Nicarágua '),
       (' Níger '),
       (' Nigéria '),
       (' Niue, Ilha '),
       (' Norfolk, Ilha '),
       (' Noruega '),
       (' Nova Caledônia '),
       (' Nova Zelândia '),
       (' Omã '),
       (' Pacífico, Ilhas do (Possessão dos EUA) '),
       (' Paises Baixos (Holanda) '),
       (' Palau '),
       (' Palestina '),
       (' Panamá '),
       (' Papua Nova Guiné '),
       (' Paquistão '),
       (' Paraguai '),
       (' Peru '),
       (' Pitcairn, Ilha '),
       (' Polinésia Francesa '),
       (' Polônia, República da '),
       (' Porto Rico '),
       (' Portugal '),
       (' Quênia '),
       (' Quirguiz, República '),
       (' Reino Unido '),
       (' República Centro '),
       (' República Dominicana '),
       (' Reunião, Ilha '),
       (' Romênia '),
       (' Ruanda '),
       (' Rússia, Federacão da '),
       (' Saara Ocidental '),
       (' Salomão, Ilhas '),
       (' Samoa '),
       (' Samoa Americana '),
       (' San Marino '),
       (' Santa Helena '),
       (' Santa Lúcia '),
       (' São Bartolomeu '),
       (' São Cristovão e Neves, Ilhas '),
       (' São Martinho, Ilha de (Parte Francesa) '),
       (' São Martinho, Ilha de (Parte Holandesa) '),
       (' São Pedro e Miquelon '),
       (' Sao Tomé e Príncipe, Ilhas '),
       (' São Vicente e Granadinas '),
       (' Senegal '),
       (' Serra Leoa '),
       (' Sérvia '),
       (' Seychelles '),
       (' Síria, República Árabe da '),
       (' Somália '),
       (' Sri Lanka '),
       (' Sudão '),
       (' Sudão do Sul '),
       (' Suécia '),
       (' Suíça '),
       (' Suriname '),
       (' Svalbard e Jan Mayen '),
       (' Tadjiquistão, República do '),
       (' Tailândia '),
       (' Tanzânia, Rep. Unida da '),
       (' Tcheca, República '),
       (' Terras Austrais Francesas '),
       (' Território Brit. Oc. Índico '),
       (' Timor Leste '),
       (' Togo '),
       (' Tonga '),
       (' Toquelau, Ilhas '),
       (' Trinidad e Tobago '),
       (' Tunísia '),
       (' Turcas e Caicos, Ilhas '),
       (' Turcomenistão, República do '),
       (' Turquia '),
       (' Tuvalu '),
       (' Ucrânia '),
       (' Uganda '),
       (' Uruguai '),
       (' Uzbequistao, República do '),
       (' Vanuatu '),
       (' Vaticano, Est. da Cidade do '),
       (' Venezuela '),
       (' Vietnã '),
       (' Virgens, Ilhas (Britânicas) '),
       (' Virgens, Ilhas (EUA) '),
       (' Wallis e Futuna, Ilhas '),
       (' Zâmbia '),
       (' Zimbábue ')
ON CONFLICT DO NOTHING;

INSERT INTO instrucao (descricao)
VALUES (' Analfabeto, inclusive o que, embora tenha recebido instrução, não se alfabetizou '),
       (' Até o 5° ano incompleto do Ensino Fundamental (antiga 4° série) ou que se tenha alfabetizado sem ter frequentado escola regular '),
       (' 5° ano completo do Ensino Fundamental '),
       (' Do 6° ao 9° ano do Ensino Fundamental incompleto (antiga 5° a 8° série) '),
       (' Ensino Fundamental Completo '),
       (' Ensino Médio incompleto '),
       (' Ensino Médio completo '),
       (' Educação Superior incompleta '),
       (' Educação Superior completa '),
       (' Pós '),
       (' Mestrado completo '),
       (' Doutorado completo ')
ON CONFLICT DO NOTHING;

INSERT INTO tipo_endereco (descricao)
VALUES (' Área '),
       (' Área Verde '),
       (' Acesso '),
       (' Acampamento '),
       (' Acesso Local '),
       (' Adro '),
       (' Área Especial '),
       (' Aeroporto '),
       (' Alameda '),
       (' Aldeia '),
       (' Avenida Marginal Direita '),
       (' Avenida Marginal Esquerda '),
       (' Anel Viário '),
       (' Antiga Estrada '),
       (' Artéria '),
       (' Alto '),
       (' Atalho '),
       (' Avenida '),
       (' Avenida Contorno '),
       (' Avenida Marginal '),
       (' Avenida Velha '),
       (' Balneário '),
       (' Beco '),
       (' Buraco '),
       (' Belvedere '),
       (' Bloco '),
       (' Balão '),
       (' Blocos '),
       (' Bulevar '),
       (' Bosque '),
       (' Boulevard '),
       (' Baixa '),
       (' Cais '),
       (' Calçada '),
       (' Caminho '),
       (' Canal '),
       (' Chácara '),
       (' Chapadão '),
       (' Ciclovia '),
       (' Circular '),
       (' Conjunto '),
       (' Conjunto Mutirão '),
       (' Complexo Viário '),
       (' Colônia '),
       (' Comunidade '),
       (' Condomínio '),
       (' Condomínio '),
       (' Corredor '),
       (' Campo '),
       (' Córrego '),
       (' Contorno '),
       (' Descida '),
       (' Desvio '),
       (' Distrito '),
       (' Entre Bloco '),
       (' Estrada Intermunicipal '),
       (' Enseada '),
       (' Entrada Particular '),
       (' Entre Quadra '),
       (' Escada '),
       (' Escadaria '),
       (' Estrada Estadual '),
       (' Estrada Vicinal '),
       (' Estrada de Ligação '),
       (' Estrada Municipal '),
       (' Esplanada '),
       (' Estrada de Servidão '),
       (' Estrada '),
       (' Estrada Velha '),
       (' Estrada Antiga '),
       (' Estação '),
       (' Estádio '),
       (' Estância '),
       (' Estrada Particular '),
       (' Estacionamento '),
       (' Evangélica '),
       (' Elevada '),
       (' Eixo Industrial '),
       (' Favela '),
       (' Fazenda '),
       (' Ferrovia '),
       (' Fonte '),
       (' Feira '),
       (' Forte '),
       (' Galeria '),
       (' Granja '),
       (' Núcleo Habitacional '),
       (' Ilha '),
       (' Igarapé '),
       (' Indeterminado '),
       (' Ilhota '),
       (' Jardim '),
       (' Jardinete '),
       (' Ladeira '),
       (' Lagoa '),
       (' Lago '),
       (' Loteamento '),
       (' Largo '),
       (' Lote '),
       (' Mercado '),
       (' Marina '),
       (' Modulo '),
       (' Projeção '),
       (' Morro '),
       (' Monte '),
       (' Núcleo '),
       (' Núcleo Rural '),
       (' Outros '),
       (' Outeiro '),
       (' Paralela '),
       (' Passeio '),
       (' Pátio '),
       (' Praça '),
       (' Praça de Esportes '),
       (' Parada '),
       (' Paradouro '),
       (' Ponta '),
       (' Praia '),
       (' Prolongamento '),
       (' Parque Municipal '),
       (' Parque '),
       (' Parque Residencial '),
       (' Passarela '),
       (' Passagem '),
       (' Passagem de Pedestre '),
       (' Passagem Subterrânea '),
       (' Ponte '),
       (' Porto '),
       (' Quadra '),
       (' Quinta '),
       (' Quintas '),
       (' Rua '),
       (' Rua Integração '),
       (' Rua de Ligação '),
       (' Rua Particular '),
       (' Rua Velha '),
       (' Ramal '),
       (' Recreio '),
       (' Recanto '),
       (' Retiro '),
       (' Residencial '),
       (' Reta '),
       (' Ruela '),
       (' Rampa '),
       (' Rodo Anel '),
       (' Rodovia '),
       (' Rotula '),
       (' Rua de Pedestre '),
       (' Margem '),
       (' Retorno '),
       (' Rotatória '),
       (' Segunda Avenida '),
       (' Sitio '),
       (' Servidão '),
       (' Setor '),
       (' Subida '),
       (' Trincheira '),
       (' Terminal '),
       (' Trecho '),
       (' Trevo '),
       (' Túnel '),
       (' Travessa '),
       (' Travessa Particular '),
       (' Travessa Velha '),
       (' Unidade '),
       (' Via '),
       (' Via Coletora '),
       (' Via Local '),
       (' Via de Acesso '),
       (' Vala '),
       (' Via Costeira '),
       (' Viaduto '),
       (' Via Expressa '),
       (' Vereda '),
       (' Via Elevado '),
       (' Vila '),
       (' Viela '),
       (' Vale '),
       (' Via Litorânea '),
       (' Via de Pedestre '),
       (' Variante '),
       (' Zigue-Zague ')
ON CONFLICT DO NOTHING;

INSERT INTO tipo_dependente (descricao)
VALUES (' Cônjuge '),
       (' Companheiro(a) com o(a) qual tenha filho ou viva há mais de 5 (cinco) anos ou possua declaração de união estável '),
       (' Filho(a) ou enteado(a) '),
       (' Filho(a) ou enteado(a), universitário(a) ou cursando escola técnica de 2° grau '),
       (' Irmão(ã), neto(a) ou bisneto(a) sem arrimo dos pais, do(a) qual detenha a guarda judicial '),
       (' Irmão(ã), neto(a) ou bisneto(a) sem arrimo dos pais, universitário(a) ou cursando escola técnica de 2°; grau, do(a) qual detenha a guarda judicial '),
       (' Pais, avós e bisavós '),
       (' Menor pobre do qual detenha a guarda judicial '),
       (' A pessoa absolutamente incapaz, da qual seja tutor ou curador '),
       (' Ex cônjuge '),
       (' Agregado/Outros ')
ON CONFLICT DO NOTHING;
