services:
  #  app:
  #    build: .
  #    ports:
  #      - 8080:8080
  #    depends_on:
  #      - db
  #    env_file:
  #      - variables-dev.env

  db:
    image: postgres:15
    env_file:
      - variables-dev.env
    ports:
      - "5432:5432"