services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - variables-dev.env
    networks:
      - spring_pg

  db:
    image: postgres:15
    env_file:
      - variables-dev.env
    ports:
      - "5432:5432"
    networks:
      - spring_pg

networks:
  spring_pg:
      driver: bridge